/**
 * Multiviewer over streaming — an add-on to the control bridge.
 *
 * The bridge steers cameras over CGI/VISCA; their live picture rides a separate
 * stream (RTSP/HLS/MJPEG), as `docs/live-video.md` sets out. This module turns
 * the configured stream URLs into the artefacts that show all cameras at once,
 * without adding a runtime dependency to the bridge itself:
 *
 *  - a `go2rtc.yaml` that re-serves each RTSP feed as low-latency WebRTC (the
 *    path `live-video.md` recommends for the RTSP/NDI PTZ world);
 *  - a launch script that opens a local multiviewer — mpv with one window per
 *    camera, or an ffmpeg mosaic when mpv is absent;
 *  - a VLC script that opens one window per stream and tiles them.
 *
 * Pure string builders: they take the streams and return text, so they are
 * fully unit-testable and reach no network. Nothing here transcodes on its own
 * — the scripts drive tools the operator already has (go2rtc, mpv, ffmpeg, VLC).
 */

export interface MultiviewSource {
  /** Shown on the tile and used as the go2rtc stream id (slugged). */
  label: string;
  /** RTSP/HLS/MJPEG stream address. */
  streamUrl: string;
}

/** A go2rtc-safe stream id: lower-case, ascii, dash-separated. */
export function slug(value: string): string {
  return (
    value
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-|-$/g, '') || 'stream'
  );
}

export interface Grid {
  columns: number;
  rows: number;
}

/** A near-square grid for n tiles: 1→1×1, 2→2×1, 4→2×2, 9→3×3, … */
export function gridFor(count: number): Grid {
  if (count <= 1) return { columns: 1, rows: 1 };
  const columns = Math.ceil(Math.sqrt(count));
  const rows = Math.ceil(count / columns);
  return { columns, rows };
}

/**
 * go2rtc config that re-serves every stream as WebRTC. Start with
 * `go2rtc -c go2rtc.yaml`; the web UI on :1984 then carries each stream.
 */
export function buildGo2rtcConfig(sources: MultiviewSource[]): string {
  const lines = [
    '# go2rtc.yaml — generated by the LZ Camera Bridge multiviewer',
    '#',
    '# Start:  go2rtc -c go2rtc.yaml',
    '# Web UI: http://localhost:1984',
    '',
    'api:',
    '  listen: ":1984"',
    '  origin: "*"',
    '',
    'webrtc:',
    '  candidates:',
    '    - stun:8555',
    '',
    'streams:',
  ];
  const used = new Map<string, number>();
  for (const s of sources) {
    let id = slug(s.label);
    // Keep ids unique when two labels slug to the same thing.
    const seen = used.get(id) ?? 0;
    used.set(id, seen + 1);
    if (seen > 0) id = `${id}-${seen + 1}`;
    lines.push(`  ${id}:`);
    lines.push(`    - ${s.streamUrl}`);
  }
  lines.push('');
  return lines.join('\n');
}

const MPV_FLAGS = [
  '--no-border',
  '--no-osc',
  '--profile=low-latency',
  '--untimed',
  '--no-cache',
  '--rtsp-transport=tcp',
  '--loop-file=inf',
  '--really-quiet',
];

interface Tile {
  x: number;
  y: number;
  width: number;
  height: number;
}

export function tilePositions(count: number, screenWidth: number, screenHeight: number): Tile[] {
  const { columns, rows } = gridFor(count);
  const width = Math.floor(screenWidth / columns);
  const height = Math.floor(screenHeight / rows);
  return Array.from({ length: count }, (_, i) => ({
    x: (i % columns) * width,
    y: Math.floor(i / columns) * height,
    width,
    height,
  }));
}

/**
 * A local multiviewer launcher (bash). Prefers mpv with one window per camera;
 * where mpv is absent, ffmpeg composes a mosaic and ffplay shows it. Both are
 * also looked for in `./ffmpeg-portable` so a first-time setup needs no install.
 */
export function buildLaunchScript(
  sources: MultiviewSource[],
  screenWidth = 1920,
  screenHeight = 1080,
): string {
  const positions = tilePositions(sources.length, screenWidth, screenHeight);
  const { columns, rows } = gridFor(sources.length);
  const tileW = Math.floor(screenWidth / columns);
  const tileH = Math.floor(screenHeight / rows);
  const total = columns * rows;

  const mpvLines = sources
    .map((s, i) => {
      const p = positions[i];
      return `  "$MPV" ${MPV_FLAGS.join(' ')} --geometry=${p.width}x${p.height}+${p.x}+${p.y} --title="${s.label}" "${s.streamUrl}" &`;
    })
    .join('\n');

  const ffInputs = sources
    .map((s) => `    -rtsp_transport tcp -fflags nobuffer -flags low_delay -i "${s.streamUrl}"`)
    .join(' \\\n');
  const scale = sources
    .map((_, i) => `[${i}:v]scale=${tileW}:${tileH}[t${i}]`)
    .concat(
      Array.from({ length: total - sources.length }, (_, k) => `color=c=black:s=${tileW}x${tileH}[t${sources.length + k}]`),
    )
    .join(';');
  const layout = Array.from({ length: total }, (_, i) => {
    const col = i % columns;
    const row = Math.floor(i / columns);
    const x = col === 0 ? '0' : Array.from({ length: col }, (_, k) => `w${k}`).join('+');
    const y = row === 0 ? '0' : Array.from({ length: row }, () => 'h0').join('+');
    return `${x}_${y}`;
  }).join('|');
  const refs = Array.from({ length: total }, (_, i) => `[t${i}]`).join('');

  return [
    '#!/bin/bash',
    '# Multiviewer launcher — generated by the LZ Camera Bridge',
    'cd "$(dirname "$0")"',
    '',
    'MPV=""',
    'command -v mpv >/dev/null 2>&1 && MPV="$(command -v mpv)"',
    '[ -z "$MPV" ] && [ -x /opt/homebrew/bin/mpv ] && MPV=/opt/homebrew/bin/mpv',
    '',
    'if [ -n "$MPV" ]; then',
    '  pkill -f "mpv .*rtsp://" 2>/dev/null || true',
    mpvLines,
    '  echo "Multiviewer running (mpv). Close each window with q, or Ctrl+C here."',
    '  wait',
    '  exit 0',
    'fi',
    '',
    'FF=""; FP=""',
    'command -v ffmpeg >/dev/null 2>&1 && FF="$(command -v ffmpeg)"',
    'command -v ffplay >/dev/null 2>&1 && FP="$(command -v ffplay)"',
    'for d in /opt/homebrew/bin /usr/local/bin ./ffmpeg-portable; do',
    '  [ -z "$FF" ] && [ -x "$d/ffmpeg" ] && FF="$d/ffmpeg"',
    '  [ -z "$FP" ] && [ -x "$d/ffplay" ] && FP="$d/ffplay"',
    'done',
    'if [ -z "$FF" ] || [ -z "$FP" ]; then',
    '  echo "Neither mpv nor ffmpeg found. Install one, or fetch a portable ffmpeg."',
    '  exit 1',
    'fi',
    'echo "Multiviewer running (ffmpeg mosaic). Close the window or Ctrl+C here."',
    '"$FF" -hide_banner -loglevel warning \\',
    ffInputs + ' \\',
    `    -filter_complex "${scale};${refs}xstack=inputs=${total}:layout=${layout}[v]" \\`,
    '    -map "[v]" -f matroska - | "$FP" -hide_banner -loglevel warning -fflags nobuffer -flags low_delay -window_title "LZ Camera Bridge Multiviewer" -i -',
    '',
  ].join('\n');
}

/**
 * A VLC launcher (bash) that opens one window per stream and tiles them over
 * the screen. Separate windows need `--no-one-instance`; the screen size is
 * read at run time so the grid fits the actual display.
 */
export function buildVlcWindowsScript(sources: MultiviewSource[]): string {
  const { columns, rows } = gridFor(sources.length);
  const launches = sources
    .map((s, i) => {
      const col = i % columns;
      const row = Math.floor(i / columns);
      return [
        `# ${s.label}`,
        `X=$(( col_w * ${col} )); Y=$(( row_h * ${row} + TOP ))`,
        `"$VLC" --no-one-instance --started-from-file --no-video-title-show \\`,
        `  --video-x=$X --video-y=$Y --width=$col_w --height=$row_h \\`,
        `  --network-caching=300 --rtsp-tcp "${s.streamUrl}" >/dev/null 2>&1 &`,
        '',
      ].join('\n');
    })
    .join('\n');

  return [
    '#!/bin/bash',
    '# VLC multiviewer, one window per camera — generated by the LZ Camera Bridge',
    'cd "$(dirname "$0")"',
    '',
    'VLC=""',
    'for c in "/Applications/VLC.app/Contents/MacOS/VLC" "$HOME/Applications/VLC.app/Contents/MacOS/VLC"; do',
    '  [ -x "$c" ] && VLC="$c" && break',
    'done',
    'if [ -z "$VLC" ] && command -v vlc >/dev/null 2>&1; then VLC="$(command -v vlc)"; fi',
    'if [ -z "$VLC" ]; then echo "VLC not found: https://www.videolan.org/vlc/"; exit 1; fi',
    '',
    "BOUNDS=$(osascript -e 'tell application \"Finder\" to get bounds of window of desktop' 2>/dev/null)",
    "SW=$(echo \"$BOUNDS\" | awk -F', ' '{print $3}')",
    "SH=$(echo \"$BOUNDS\" | awk -F', ' '{print $4}')",
    '[ -z "$SW" ] && SW=1920',
    '[ -z "$SH" ] && SH=1080',
    'TOP=25',
    `COLS=${columns}`,
    `ROWS=${rows}`,
    'col_w=$(( SW / COLS ))',
    'row_h=$(( (SH - TOP) / ROWS ))',
    '',
    launches,
    'echo "VLC multiviewer running. Close the windows or Ctrl+C here."',
    'wait',
    '',
  ].join('\n');
}
